routes/web.php
<?php

use App\Http\Controllers\FolioController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RolController;
use App\Http\Controllers\UsuarioController;
use App\Http\Controllers\RegistroCivilController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function(){return view('auth.login');});
Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', [HomeController::class, 'index'])->name('home');
    Route::get('folios/limpiar', [FolioController::class, 'limpiar'])->name('folios.limpiar');
    Route::get('historial/limpiarHistorial', [FolioController::class, 'limpiar_hisrial'])->name('folios.limpiarHistorial');
    Route::resource('roles', RolController::class);
    Route::resource('usuarios', UsuarioController::class);
    Route::resource('folios', FolioController::class);
    Route::resource('registroCivil', RegistroCivilController::class);
    Route::get('/consulta', [FolioController::class, 'getFormularioConsulta'])->name('consulta');
    Route::post('/consulta', [FolioController::class, 'postFormularioConsulta'])->name('postconsulta');
    Route::get('/error/{registro_id}', [FolioController::class, 'getErrorConsulta'])->name('errorconsulta');
    // Route::post('/historial', [FolioController::class, 'postHistorial'])->name('historialComprobantes');
    Route::get('/historial', [FolioController::class, 'postHistorial'])->name('historialComprobantes');
    Route::get('/descargar', [FolioController::class, 'postdescargar'])->name('postdescargar');
    // Route::post('/descargar', [FolioController::class, 'postdescargar'])->name('postdescargar');
    Route::get('/contacto', [HomeController::class, 'contacto'])->name('contacto');
    Route::get('folios/{folio}/delete', [FolioController::class, 'destroy'])->name('folios.delete');
    Route::get('registroCivil/{registroCivil}/delete', [RegistroCivilController::class, 'destroy'])->name('registroCivil.delete');
    Route::get('roles/{rol}/delete', [RolController::class, 'destroy'])->name('roles.delete');
    Route::get('usuarios/{usuario}/delete', [UsuarioController::class, 'destroy'])->name('usuarios.delete');
    Route::get('/registroCivilImportar/{registroCivil}', [RegistroCivilController::class, 'importarEscaneados'])->name('registroCivil.importar');
});

resources/views/registros/crear.blade.php
@extends('adminlte::page')

@section('content')
{{ mostrar_miga([['link' => route('home'), 'titulo' => 'Inicio'], ['link' => route('registroCivil.index'), 'titulo' => 'Gestión de registros'], ['titulo' => 'Cargar registro']]) }}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">Cargar registro</div>
                    <div class="card-body">
                        @include('errors')
                        {!! Form::open(['route' => 'registroCivil.store', 'method' => 'POST']) !!}
                        @csrf
                        <br>
                        <div class="row">
                            <div class="col-lg-4">
                                <label for="codigoRegistro" class="form-label">Código del registro</label>
                                {{ Form::number('codigoRegistro', null, ['class' => 'form-control', 'minlength' => '7', 'maxlength' => '7', 'required']) }}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-lg-4">
                                <label for="nombreRegistro" class="form-label">Nombre</label>
                                {{ Form::text('nombreRegistro', null, ['class' => 'form-control', 'minlength' => '3', 'maxlength' => '30', 'required']) }}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-lg-4">
                                <label for="emailRegistro" class="form-label">Email</label>
                                {{ Form::text('emailRegistro', null, ['class' => 'form-control', 'minlength' => '3', 'maxlength' => '50', 'required']) }}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-lg-4">
                                <label for="carpetaRegistro" class="form-label">Carpeta Archivos</label>
                                {{ Form::select('carpetaRegistro', $carpetasRegistros, null, ['placeholder' => 'Seleccione una opción', 'class' => 'form-control']) }}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-lg-4">
                                <label for="donde_consultar" class="form-label">Donde Consultar</label>
                                {{ Form::select('donde_consultar', $donde_consultar, null, ['placeholder' => 'Seleccione una opción', 'class' => 'form-control', 'required']) }}
                            </div>
                        </div>                                                
                        <hr>
                        <div class="row">
                            <div class="col text-right">
                                <a class="btn btn-danger" href="{{ route('registroCivil.index') }}">Cancelar&nbsp;&nbsp;<i class="fa fa-times"
                                        aria-hidden="true"></i></a>
                                <button type="submit" class="btn btn-success">Guardar&nbsp;&nbsp;<i
                                        class="fa fa-save"></i></button>
                            </div>
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/registros/editar.blade.php
@extends('adminlte::page')

@section('content')
{{ mostrar_miga([['link' => route('home'), 'titulo' => 'Inicio'], ['link' => route('registroCivil.index'), 'titulo' => 'Gestión de registros'], ['titulo' => 'Editar registro']]) }}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header"> Editar registro
                    </div>
                    <div class="card-body">
                        @include('errors')
                        {!! Form::model($registros, ['method' => 'PUT', 'route' => ['registroCivil.update', $registros->id]]) !!}
                        @csrf
                        <br>
                        <div class="row">
                            <div class="col-lg-4">
                                <label for="codigoRegistro" class="form-label">Código del registro</label>
                                {{ Form::number('codigoRegistro', null, ['class' => 'form-control', 'minlength' => '7', 'maxlength' => '7', 'disabled']) }}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-lg-4">
                                <label for="nombreRegistro" class="form-label">Nombre del registro</label>
                                {{ Form::text('nombreRegistro', null, ['class' => 'form-control', 'maxlength' => '30', 'required']) }}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-lg-4">
                                <label for="emailRegistro" class="form-label">Email</label>
                                {{ Form::text('emailRegistro', null, ['class' => 'form-control', 'maxlength' => '50', 'required']) }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-4">
                                <label for="carpetaRegistro" class="form-label">Carpeta Archivos</label>
                                {{ Form::select('carpetaRegistro', $carpetasRegistros, null, ['placeholder' => 'Seleccione una opción', 'class' => 'form-control']) }}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-lg-4">
                                <label for="donde_consultar" class="form-label">Donde Consultar</label>
                                {{ Form::select('donde_consultar', $donde_consultar, null, ['placeholder' => 'Seleccione una opción', 'class' => 'form-control', 'required']) }}
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col text-right">
                                <a class="btn btn-danger" href="{{ route('registroCivil.index') }}">Cancelar&nbsp;&nbsp;<i class="fa fa-times"
                                        aria-hidden="true"></i></a>
                                <button type="submit" class="btn btn-success">Guardar&nbsp;&nbsp;<i
                                        class="fa fa-save"></i></button>
                            </div>
                        </div>
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
    </div>
@endsection

resources/views/registros/index.blade.php
@extends('adminlte::page')

@section('content')
{{ mostrar_miga([['link' => route('home'), 'titulo' => 'Inicio'], ['titulo' => 'Gestión de registros']]) }}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">Gestión de Registros</div>
                    <div class="card-body">
                        @include('errors')
                        @can('crear-registros')
<!--
                            <div class="row">
                                <div class="col-lg-12 mb-1">
                                    <a class="btn btn-success float-right"
                                        href="{{ route('registroCivil.create') }}">Nuevo&nbsp;&nbsp;<span
                                            class="fa fa-plus"></span></a>
                                </div>
                            </div>
-->
                        @endcan
                        <table class="table table-striped table-responsive w-100 d-md-table">
                            <thead>
                                <th class="text-right" style="color:#fff;">Código</th>
                                <th class="text-left" style="color:#fff;">Registro</th>
                                <th class="text-left" style="color:#fff;">Email</th>
                                <th class="text-left" style="color:#fff;">Carpeta</th>
                                <th class="text-left" style="color:#fff;">Donde Consutar</th>
                                <th class="text-center" style="color:#fff;">Acciones</th>
                            </thead>
                            <tbody>
                                @foreach ($registros as $item)
                                    <tr>
                                        <td class="text-right">{{ $item->codigoRegistro }}</td>
                                        <td>{{ $item->nombreRegistro }}</td>
                                        <td>{{ $item->emailRegistro }}</td>
                                        <td>{{ $item->carpetaRegistro }}</td>
                                        @if(!empty($item->donde_consultar))
                                        <td>{{ $donde_consultar[$item->donde_consultar] }}</td>
                                        @else
                                        <td>&nbsp;</td>
                                        @endif
                                        <td class="text-center">
                                            @if (!empty($item->carpetaRegistro))
                                                <a title="Importar Escaneados" class="fa fa-file-import"
                                                    href="{{ route('registroCivil.importar', $item->id) }}"></a>
                                            @endif
                                            &nbsp;&nbsp;
                                            @can('editar-registros')
                                                <a title="Editar" class="fa fa-pen"
                                                    href="{{ route('registroCivil.edit', $item->id) }}"></a>
                                            @endcan
<!--
                                            &nbsp;&nbsp;
                                            @can('borrar-registros')
                                                <a title="Borrar" class="fa fa-trash"
                                                    href="{{ route('registroCivil.delete', $item->id) }}"
                                                    onclick="return confirm('¿Confirma que quiere eliminar este registro?')"></a>
                                            @endcan
-->                                            
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection