routes/web.php
<?php

use App\Http\Controllers\FolioController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RolController;
use App\Http\Controllers\UsuarioController;
use App\Http\Controllers\RegistroCivilController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function(){return view('auth.login');});
Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', [HomeController::class, 'index'])->name('home');
    Route::get('folios/limpiar', [FolioController::class, 'limpiar'])->name('folios.limpiar');
    Route::get('historial/limpiarHistorial', [FolioController::class, 'limpiar_hisrial'])->name('folios.limpiarHistorial');
    Route::resource('roles', RolController::class);
    Route::resource('usuarios', UsuarioController::class);
    Route::resource('folios', FolioController::class);
    Route::resource('registroCivil', RegistroCivilController::class);
    Route::get('/consulta', [FolioController::class, 'getFormularioConsulta'])->name('consulta');
    Route::post('/consulta', [FolioController::class, 'postFormularioConsulta'])->name('postconsulta');
    Route::get('/error/{registro_id}', [FolioController::class, 'getErrorConsulta'])->name('errorconsulta');
    // Route::post('/historial', [FolioController::class, 'postHistorial'])->name('historialComprobantes');
    Route::get('/historial', [FolioController::class, 'postHistorial'])->name('historialComprobantes');
    Route::get('/descargar', [FolioController::class, 'postdescargar'])->name('postdescargar');
    // Route::post('/descargar', [FolioController::class, 'postdescargar'])->name('postdescargar');
    Route::get('/contacto', [HomeController::class, 'contacto'])->name('contacto');
    Route::get('folios/{folio}/delete', [FolioController::class, 'destroy'])->name('folios.delete');
    Route::get('registroCivil/{registroCivil}/delete', [RegistroCivilController::class, 'destroy'])->name('registroCivil.delete');
    Route::get('roles/{rol}/delete', [RolController::class, 'destroy'])->name('roles.delete');
    Route::get('usuarios/{usuario}/delete', [UsuarioController::class, 'destroy'])->name('usuarios.delete');
    Route::get('/registroCivilImportar/{registroCivil}', [RegistroCivilController::class, 'importarEscaneados'])->name('registroCivil.importar');
});

app/Models/folio.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class folio extends Model
{
    use HasFactory;
    protected $fillable = ['numeroMatricula', 'registro_id', 'fechaScaneo', 'estado', 'archivo'];
}

app/Http/Controllers/FolioController.php
<?php

namespace App\Http\Controllers;

use App\Models\Comprobantes;
use App\Models\folio;
use App\Models\registroCivil;
use Auth;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Validation\ValidationException;
use DateTime;
use DB;
use GuzzleHttp\Client;
use Illuminate\Support\Facades\Response;
use App\Rules\DifferentFile;
use App\Rules\FolioUnico;

class FolioController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:ver-folio|crear-folio|editar-folio|borrar-folio', ['only' => ['index']]);
        $this->middleware('permission:crear-folio', ['only' => ['create', 'store']]);
        $this->middleware('permission:editar-folio', ['only' => ['edit', 'update']]);
        $this->middleware('permission:borrar-folio', ['only' => ['destroy']]);
    }
    
    public function limpiar(Request $request)
    {
      session()->forget(['operacion', 'filtros']);
      return redirect()->route('folios.index');
    }
    
    public function limpiar_hisrial(Request $request)
    {
      session()->forget(['operacion', 'historial']);
      return redirect()->route('historialComprobantes');
    }
    
    public function index(Request $request)
    {
        $input = [];
        if (session()->has('operacion') && session()->get('operacion') == 'folios' && !empty(session()->get('filtros'))) {
            $input = (!empty($request->all()) && session()->get('filtros') != $request->all())?$request->all():session()->get('filtros');
        } else {
            session(['operacion' => 'folios', 'filtros' => empty($request->all())?$input:$request->all()]);
            $input = session()->get('filtros');
        }

        if (!empty($input) || $request->hasAny(['busquedaMatricula', 'busquedaFechaScaneoI', 'busquedaFechaScaneoF', 'busquedaRegistro_id'])) {
            
            $query = 
                Folio::join('registro_civils', 'registro_civils.id', 'folios.registro_id')
                    ->select('folios.*', 'registro_civils.nombreRegistro', 'registro_civils.codigoRegistro', 'registro_civils.donde_consultar as origen');

            if (!empty($input['busquedaMatricula'])) {
                $query->Where('folios.numeroMatricula', 'like', '%' . $input['busquedaMatricula'] . '%');
            }
            
            if (!empty($input['busquedaFechaScaneoI']) && !empty($input['busquedaFechaScaneoF'])) {
              if ($input['busquedaFechaScaneoF'] < $input['busquedaFechaScaneoI']) {
                throw ValidationException::withMessages(["busquedaFechaScaneoF" => "La fecha de fin debe ser mayor que la fecha de inicio"]);
              }
            }
            
            if (!empty($input['busquedaFechaScaneoI'])) {
              $query->whereDate('folios.updated_at', '>=', new DateTime($input['busquedaFechaScaneoI']));
            }
            
            if (!empty($input['busquedaFechaScaneoF'])) {
              $query->whereDate('folios.updated_at', '<=', new DateTime($input['busquedaFechaScaneoF'].' 23:59:59'));
            }
            
            if (!empty($input['busquedaRegistro_id'])) {
                $query->Where('folios.registro_id', '=', $input['busquedaRegistro_id']);
            }
            
            if (!empty(Auth::user()->registro_id)) {
                $query->Where('folios.registro_id', '=', Auth::user()->registro_id);
            }
            
            $query->where('folios.estado','<>','inactivo');
            $query->where('registro_civils.donde_consultar','base');
            $query->orderBy('folios.updated_at', 'desc');
            $folios=$query->paginate(50);
            $folios->setPath('');
            // dd($folios);
        } else {
            $folios = array();
            $input = [
                'busquedaMatricula' => null, 
                'busquedaFechaScaneoI' => null, 
                'busquedaFechaScaneoF' => null, 
                'busquedaRegistro_id' => null
            ];            
        }

        $registros = DB::table('registro_civils')->where('donde_consultar', 'base')->orderBy('nombreRegistro','asc')->pluck('nombreRegistro','id');
        return view('folios.index', compact('folios', 'registros', 'input'));
    }

    public function create()
    {
        //Metodo donde levantamos formulario para crear
        $registros = DB::table('registro_civils')->where('donde_consultar', 'base')->orderBy('nombreRegistro','asc')->pluck('nombreRegistro','id');
        return view('folios.crear', compact('registros'));
    }

    public function store(Request $request)
    {
        request()->validate([
            'registro_id' => 'required|exists:registro_civils,id',
            'numeroMatricula' => 'required|max:25|min:1',
            'archivo' => 'required|max:5000|mimes:pdf'
        ]);
        request()->validate(['numeroMatricula' => [new FolioUnico($request->registro_id)]]);

        $registro = registroCivil::find($request->registro_id);
        $folio = Folio::create();
        $folio->numeroMatricula = $request->numeroMatricula;
        $folio->registro_id = $request->registro_id;
        $folio->fechaScaneo = date('Y-m-d');
        $folio->estado='activo';
        $nombreArchivo = md5($request->registro_id.$request->numeroMatricula.date('Ymdyis')).'.pdf';
        $folio->archivo = $registro->carpetaRegistro.'/'.$nombreArchivo;
        $folio->save();
        $path = $request->file('archivo')->storeAs('Archivos/'.$registro->carpetaRegistro, $nombreArchivo);
        toastr()->success('Folio creado exitosamente!', 'Aviso');        
        return redirect()->route('folios.index');
    }

    public function edit(folio $folio)
    {
        //Lo voy a usar para levantar el formulario de busqueda
        $registros = DB::table('registro_civils')->where('donde_consultar', 'base')->orderBy('nombreRegistro','asc')->pluck('nombreRegistro','id');
        $folio->fechaScaneo = date('Y-m-d', strtotime($folio['fechaScaneo']));
        return view('folios.editar', compact('registros', 'folio'));
    }

    public function update(Request $request, folio $folio)
    {
        //Este funciona como el store pero para guardar datos
        request()->validate([
            'numeroMatricula' => 'required|max:25',
            'registro_id' => 'required',
        ]);
        request()->validate(['numeroMatricula' => [new FolioUnico($request->registro_id)]]);
        
        $folio->update($request->all());
        if (!empty($request->archivo)) {
            $registro = registroCivil::find($request->registro_id);
            $nombreArchivo = md5($request->registro_id.$request->numeroMatricula.date('Ymdhis')).'.pdf';
            $folio->archivo = $registro->carpetaRegistro.'/'.$nombreArchivo;
            $path = $request->file('archivo')->storeAs('Archivos/'.$registro->carpetaRegistro, $nombreArchivo);          
            $folio->updated_at = date('Y-m-d h:i:s');
            $folio->save();
        }
        toastr()->success("Folio modificado exitosamente!", 'Aviso');
        return redirect()->route('folios.index');
    }

    public function destroy(folio $folio)
    {
        $folio = Folio::find($folio->id);
        $folio->estado ='inactivo';
        $folio->update();
        toastr()->success("Folio borrado exitosamente!", 'Aviso');
        return redirect()->route('folios.index');
    }
    
    //Funcion que arma el formulario o vista para realizar la consulta
    public function getFormularioConsulta()
    {
        $registros = DB::table('registro_civils')->orderBy('nombreRegistro','asc')->pluck('nombreRegistro','id');
        $folios = [];
        return view('folios.consultar', compact('registros', 'folios'));

    }
    
    //Funcion que busca y devuelve el folio consultado, ademas almacena los comprobantes
    public function postFormularioConsulta(Request $request)
    {
        //Metodo donde se hace todo el trabajo de guardado post consulta
        request()->validate([
            'matricula_id' => 'required|max:25|min:1',
            'registro_id' => 'required',
            'ordenPago' => 'required|file|max:2048|mimes:jpg,jpeg,png,pdf',
            'comprobantePago' => 'required|file|max:2048|mimes:jpg,jpeg,png,pdf',
        ], [
            'ordenPago.max' => 'El tamaño máximo del archivo de Orden de pago debe ser de 2 Megabytes.',
            'comprobantePago.max' => 'El tamaño máximo del archivo de Comprobante de pago debe ser de 2 Megabytes.',
        ]);
        request()->validate([
            'comprobantePago' => [new DifferentFile(hash_file('sha256', $request->file('ordenPago')))]
        ]);
        
        if ($request) {
            $nombreOrdenPago = md5('ordenPago-' . $request['matricula_id'] . '-' . date("Ymdhis")) . '.' . $request->file('ordenPago')->clientExtension();
            $request->file('ordenPago')->storeAs('Comprobantes', ($nombreOrdenPago));

            $nombreComprobantePago = md5('comprobantePago-' . $request['matricula_id'] . '-' . date("Ymdhis")) . '.' . $request->file('comprobantePago')->clientExtension();
            $request->file('comprobantePago')->storeAs('Comprobantes', ($nombreComprobantePago));

            $comprobante = new Comprobantes;
            $comprobante->ordenPago = $nombreOrdenPago;
            $comprobante->comprobantePago = $nombreComprobantePago;
            $comprobante->matricula_id = $request['matricula_id'];
            $comprobante->registro_id = $request['registro_id'];
            $comprobante->usuarioConsultor = Auth::user()->id;
            
            $registro = registroCivil::find($request->registro_id);
            // dd($registro);
            if ($registro->donde_consultar == 'base') {
                $resultado = Folio::select('numeroMatricula as numero', 'nombreRegistro as registro', DB::raw("DATE_FORMAT(folios.updated_at, '%d/%m/%Y') as fecha_alta"), 'folios.id', 'donde_consultar as origen')

resources/views/folios/consultar.blade.php
@extends('adminlte::page')

@section('content')
{{ mostrar_miga([['link' => route('home'), 'titulo' => 'Inicio'], ['titulo' => 'Consulta IN VISU']]) }}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">Consulta IN VISU</div>
                    <div class="card-body">
                        @include('errors')
                        {!! Form::open(['route' => 'postconsulta', 'method' => 'POST', 'files' => true]) !!}
                        <div class="row">
                            <div class="form-group mx-sm-3">
                                <label for="registro_id" class="form-label">Registro</label>
                                {{ Form::select('registro_id', $registros, null, ['placeholder' => 'Seleccione una opción', 'class' => 'form-control', 'required']) }}
                            </div>
                            <div class="form-group mx-sm-3">
                                <label for="matricula_id" class="form-label">Número de matrícula</label>
                                {{ Form::text('matricula_id', null, ['class' => 'form-control', 'minlength' => '1', 'maxlength' => '25', 'required']) }}
                            </div>
                        </div>
                        <hr>
                        <br>
                        <div class="row">
                            <div class="form-group mx-sm-3">
                                <label for="ordenPago" class="form-label">Orden de pago</label>
                                {{ Form::file('ordenPago', old('ordenPago'), ['class' => 'form-control', 'accept' => '.pdf, .png, .jpg, .jpeg', 'required']) }}
                            </div>
                            <div class="form-group mx-sm-3">
                                <label for="comprobantePago" class="form-label">Comprobante de pago</label>
                                {{ Form::file('comprobantePago', old('comprobantePago'), ['class' => 'form-control', 'accept' => '.pdf, .png, .jpg, .jpeg', 'required']) }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col text-right">
                                <a class="btn btn-default" href="{{ route('consulta') }}">Limpiar&nbsp;&nbsp;<span
                                        class="fa fa-eraser"></span></a>
                                <button type="submit" class="btn btn-secondary">Buscar&nbsp;&nbsp;<span
                                        class="fa fa-search"></span></button>
                            </div>
                            {!! Form::close() !!}
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/folios/crear.blade.php
@extends('adminlte::page')

@section('content')
{{ mostrar_miga([['link' => route('home'), 'titulo' => 'Inicio'], ['link' => route('folios.index'), 'titulo' => 'Gestión de folios'], ['titulo' => 'Cargar folio']]) }}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">Cargar folio</div>
                    <div class="card-body">
                        @include('errors')
                        {!! Form::open(['route' => 'folios.store', 'method' => 'POST', 'files' => true]) !!}
                        @csrf
                        {!! Form::hidden('estado', 'activo') !!}
                        @if (empty(Auth::user()->registro_id))
                            <div class="row">
                                <div class="col-lg-6">
                                    <label for="registro_id" class="form-label">Registro</label>
                                    {{ Form::select('registro_id', $registros, null, ['placeholder' => 'Seleccione una opción', 'class' => 'form-control', 'required']) }}
                                </div>
                            </div>
                        @endif
                        @if (!empty(Auth::user()->registro_id))
                            <div class="row">
                                <div class="col-lg-6">
                                    <label for="registro_id"
                                        class="form-label">{{ $registros[Auth::user()->registro_id] }}</label>
                                </div>
                            </div>
                            {!! Form::hidden('registro_id', Auth::user()->registro_id) !!}
                        @endif
                        <br>
                        <div class="row">
                            <div class="col-lg-6">
                                <label for="numeroMatricula" class="form-label">Número de Matrícula</label>
                                {{ Form::text('numeroMatricula', null, ['class' => 'form-control', 'minlength' => '1', 'maxlength' => '25', 'required']) }}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-lg-6">
                                <label for="archivo" class="form-label">Archivo</label>
                                {{ Form::file('archivo', null, ['class' => 'form-control', 'accept' => '.pdf', 'required']) }}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col text-right">
                                <a class="btn btn-danger" href="{{ route('folios.index') }}">Cancelar&nbsp;&nbsp;<i class="fa fa-times"
                                        aria-hidden="true"></i></a>
                                <button type="submit" class="btn btn-success">Guardar&nbsp;&nbsp;<i
                                        class="fa fa-save"></i></button>
                            </div>
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/folios/editar.blade.php
@extends('adminlte::page')

@section('content')
{{ mostrar_miga([['link' => route('home'), 'titulo' => 'Inicio'], ['link' => route('folios.index'), 'titulo' => 'Gestión de folios'], ['titulo' => 'Editar folio']]) }}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">Editar Folio</div>
                    <div class="card-body">
                        @include('errors')
                        {!! Form::model($folio, ['method' => 'PATCH', 'route' => ['folios.update', $folio->id], 'files' => true]) !!}
                        @csrf
                        {!! Form::hidden('estado', 'activo') !!}
                        @if (empty(Auth::user()->registro_id))
                            <div class="row">
                                <div class="col-lg-6">
                                    <label for="registro_id" class="form-label">Registro</label>
                                    {{ Form::select('registro_id', $registros, null, ['placeholder' => 'Seleccione una opción', 'class' => 'form-control', 'required']) }}
                                </div>
                            </div>
                        @endif
                        @if (!empty(Auth::user()->registro_id))
                            <div class="row">
                                <div class="col-lg-6">
                                    <label for="registro_id"
                                        class="form-label">{{ $registros[Auth::user()->registro_id] }}</label>
                                </div>
                            </div>
                            {!! Form::hidden('registro_id', Auth::user()->registro_id) !!}
                        @endif
                        <br>
                        <div class="row">
                            <div class="col-lg-6">
                                <label for="numeroMatricula" class="form-label">Número de Matrícula</label>
                                {{ Form::text('numeroMatricula', null, ['class' => 'form-control', 'minlength' => '1', 'maxlength' => '25', 'required']) }}
                            </div>
                        </div>
                        <br>
                        <div class="row">

                            <div class="col-lg-6">
								@if ($folio->archivo)
									<span>Esta matricula contiene un archivo cargado, puede descargarlo para ver su contenido </span>
									<a title="Descargar" class="fa fa-download" href="{{ route('postdescargar', ['id' => $folio->id, 'origen' => 'base']) }}"></a>
								@endif
								<br>
								<br>
                                <label for="archivo" class="form-label">Al seleccionar otro archivo reemplazará el actual.</label>
                                {{ Form::file('archivo', null, ['class' => 'form-control', 'accept' => '.pdf']) }}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col text-right">
                                <a class="btn btn-danger" href="{{ route('folios.index') }}">Cancelar&nbsp;&nbsp;<i class="fa fa-times"
                                        aria-hidden="true"></i></a>
                                <button type="submit" class="btn btn-success">Guardar&nbsp;&nbsp;<i
                                        class="fa fa-save"></i></button>
                            </div>
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/folios/index.blade.php
@extends('adminlte::page')

@section('content')
{{ mostrar_miga([['link' => route('home'), 'titulo' => 'Inicio'], ['titulo' => 'Gestión de folios']]) }}
<div class="container-fluid">
    <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">Gestión de folios</div>
                    <div class="card-body">
										@include('errors')								
										{!! Form::open(['route' => 'folios.index', 'method' => 'GET','role'=>'search']) !!}
										@csrf
										<div class="row">
											@if (empty(Auth::user()->registro_id))
											<div class="col-lg-6">
												<label for="busquedaRegistro_id" class="form-label">Registro</label>
												{{ Form::select('busquedaRegistro_id', $registros, @$input['busquedaRegistro_id'], ['class' => 'form-control', 'placeholder' => 'Seleccione una opción']) }}
											</div>
											@endif
											<div class="col-lg-6">
												<label for="busquedaMatricula" class="form-label">Número de matrícula</label>
												{{ Form::text('busquedaMatricula', @$input['busquedaMatricula'], ['class' => 'form-control', 'minlength' => '1', 'maxlength' => '25', 'placeholder' => 'Número de matrícula']) }}
											</div>
										</div>
										
										<div class="row">
											<div class="col-lg-6 mt-4">
												<label class="form-label">Fecha de digitalización</label><br>
											</div>
										</div>
										<div class="row">
											<div class="col-lg-6">
												<label for="busquedaFechaScaneoI" class="form-label">Desde</label>
												{{ Form::date('busquedaFechaScaneoI', @$input['busquedaFechaScaneoI'], ['class' => 'form-control']) }}
											</div>
											<div class="col-lg-6">
												<label for="busquedaFechaScaneoF" class="form-label">Hasta</label>
												{{ Form::date('busquedaFechaScaneoF', @$input['busquedaFechaScaneoF'], ['class' => 'form-control']) }}
											</div>
										</div>
										<br><div class="row">
												<div class="col text-right">
												<a class="btn btn-default" href="{{ route('folios.limpiar') }}">Limpiar&nbsp;&nbsp;<span class="fa fa-eraser"></span></a>
												<button type="submit" class="btn btn-secondary">Buscar&nbsp;&nbsp;<span class="fa fa-search"></span></button>
												</div>
										</div>
                    {!! Form::close() !!}
                    <hr>
                    @can('crear-folio')
										<div class="row mb-1">
											<div class="col-lg-12">
												<a class="btn btn-success float-right" href="{{ route('folios.create') }}">Nuevo&nbsp;&nbsp;<span class="fa fa-plus"></span></a>
											</div>
										</div>
                    @endcan
                    <table class="table table-striped table-responsive w-100 d-md-table">
                        <thead>
                            <th class="text-right" style="color:#fff;">Número de matrícula</th>
                            <th class="text-left" style="color:#fff;">Registro</th>
                            <th class="text-center" style="color:#fff;">Fecha de digitalización</th>
                            <th class="text-center" style="color:#fff;">Archivo</th>
                            <th class="text-center" style="color:#fff;">
														@can('editar-folio', 'borrar-folio')
															Acciones
														@endcan
														</th>
                        </thead>
                        <tbody>
												@if(count($folios) == 0)
												<tr><td colspan="5" class="text-center">No se encontraron datos</td></tr>
												@endif
                            @foreach ($folios as $value)
                            <tr>
                                <td class="text-right">{{ $value->numeroMatricula }}</td>
                                <td>{{ $value->nombreRegistro }}</td>
																<td class="text-center">{{ date('d/m/Y h:i:s', strtotime($value->updated_at)) }}</td>
																<td class="text-center">
                                   <a title="Descargar" class="fa fa-download" href="{{ route('postdescargar', ['id' => $value->id, 'origen' => $value->origen ]) }}"></a>
                                </td>
                                <td class="text-center">
									@can('editar-folio')
                                    <a title="Editar" class="fa fa-pen" href="{{ route('folios.edit', $value->id) }}"></a>
                                    @endcan
									&nbsp;&nbsp;
									@can('borrar-folio')
									<a title="Borrar" class="fa fa-trash" href="{{ route('folios.delete', $value->id) }}" onclick="return confirm('¿Confirma que quiere eliminar este folio?')"></a>
                                    @endcan
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>

                        @if (count($folios) > 0)
                            <div class="pagination justify-content-end">
                                {!! $folios->appends($input)->links() !!}
                            </div>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/folios/resultado.blade.php
@extends('adminlte::page')

@section('content')
{{ mostrar_miga([['link' => route('home'), 'titulo' => 'Inicio'], ['link' => route('consulta'), 'titulo' => 'Consulta IN VISU'], ['titulo' => 'Resultado']]) }}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">Resultado de la consulta IN VISU</div>
                    <div class="card-body">
                        @if (!empty($resultado[0]))
                            <table class="table table-striped table-resposive w-100">
                                <thead>
                                    <th class="text-left" style="color:#fff;">Registro</th>
                                    <th class="text-center" style="color:#fff;">Fecha de digitalización</th>
                                    <th class="text-right" style="color:#fff;">Número de matrícula</th>
                                    <th class="text-center" style="color:#fff;">Acciones</th>
                                </thead>
                                <tbody>
                                    @foreach ($resultado as $value)
                                        <tr>
                                            <td>{{ $value->registro }}</td>
                                            <td class="text-center">{{ $value->fecha_alta }}</td>
                                            <td class="text-right">{{ $value->numero }}</td>
                                            <td class="text-center">
                                                <a title="Descargar" class="fa fa-download"
                                                    href="{{ route('postdescargar', ['id' => $value->id, 'origen' => $value->origen]) }}"></a>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        @endif
                        @if (!empty($mensaje))
                            <p class="text-justify"> {{ $mensaje }}</p>
                            <p class="text-justify"><i>{{ $mensajeInfo }}</i></p>
                        @endif
                        <hr>
                        <div class="row">
                            <div class="col text-right">
                                <a class="btn btn-secondary" href="{{ route('consulta') }}">Consultar otra matrícula&nbsp;&nbsp;<span
                                        class="fa fa-search"></span></a>
                            </div>
                            <div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        @endsection