routes/web.php
<?php

use App\Http\Controllers\FolioController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RolController;
use App\Http\Controllers\UsuarioController;
use App\Http\Controllers\RegistroCivilController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function(){return view('auth.login');});
Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', [HomeController::class, 'index'])->name('home');
    Route::get('folios/limpiar', [FolioController::class, 'limpiar'])->name('folios.limpiar');
    Route::get('historial/limpiarHistorial', [FolioController::class, 'limpiar_hisrial'])->name('folios.limpiarHistorial');
    Route::resource('roles', RolController::class);
    Route::resource('usuarios', UsuarioController::class);
    Route::resource('folios', FolioController::class);
    Route::resource('registroCivil', RegistroCivilController::class);
    Route::get('/consulta', [FolioController::class, 'getFormularioConsulta'])->name('consulta');
    Route::post('/consulta', [FolioController::class, 'postFormularioConsulta'])->name('postconsulta');
    Route::get('/error/{registro_id}', [FolioController::class, 'getErrorConsulta'])->name('errorconsulta');
    // Route::post('/historial', [FolioController::class, 'postHistorial'])->name('historialComprobantes');
    Route::get('/historial', [FolioController::class, 'postHistorial'])->name('historialComprobantes');
    Route::get('/descargar', [FolioController::class, 'postdescargar'])->name('postdescargar');
    // Route::post('/descargar', [FolioController::class, 'postdescargar'])->name('postdescargar');
    Route::get('/contacto', [HomeController::class, 'contacto'])->name('contacto');
    Route::get('folios/{folio}/delete', [FolioController::class, 'destroy'])->name('folios.delete');
    Route::get('registroCivil/{registroCivil}/delete', [RegistroCivilController::class, 'destroy'])->name('registroCivil.delete');
    Route::get('roles/{rol}/delete', [RolController::class, 'destroy'])->name('roles.delete');
    Route::get('usuarios/{usuario}/delete', [UsuarioController::class, 'destroy'])->name('usuarios.delete');
    Route::get('/registroCivilImportar/{registroCivil}', [RegistroCivilController::class, 'importarEscaneados'])->name('registroCivil.importar');
});

app/Http/Controllers/UsuarioController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Models\Role;
use App\Models\registroCivil;
use App\Models\comprobantes;

class UsuarioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    { 
        $input = [];
        if (session()->has('operacion') && session()->get('operacion') == 'usuarios' && !empty(session()->get('filtros'))) {
            $input = (!empty($request->all()) && session()->get('filtros') != $request->all())?$request->all():session()->get('filtros');
        } else {
            session(['operacion' => 'usuarios', 'filtros' => empty($request->all())?$input:$request->all()]);
            $input = session()->get('filtros');
        }

        if (!empty($input) || $request->hasAny(['busquedaRol', 'busquedaDNI', 'busquedaNombre', 'busquedaEmail', 'busquedaEstado'])) {
            $query = User::with("roles");
            if (!empty($input['busquedaRol'])) $query->whereRelation('roles', 'role_id', '=', $input['busquedaRol']);
            if (!empty($input['busquedaDNI'])) $query->where('documento', '=', $input['busquedaDNI']);
            if (!empty($input['busquedaNombre'])) $query->where('name', 'like', '%'.$input['busquedaNombre'].'%');
            if (!empty($input['busquedaEmail'])) $query->where('email', 'like', '%'.$input['busquedaEmail'].'%');
            if (!empty($input['busquedaEstado'])) $query->where('estado', '=', $input['busquedaEstado']);
            if (!empty($input['busquedaRegistro'])) $query->where('registro_id', '=', $input['busquedaRegistro']);
            $query->orderBy('name');
            $usuarios = $query->paginate(50);
        } else {
            $usuarios = array();
        }
        $roles = DB::table('roles')->orderBy('name','asc')->pluck('name','id');
        $registros = DB::table('registro_civils')->orderBy('nombreRegistro','asc')->pluck('nombreRegistro','id');
        return view('usuarios.index', compact('usuarios', 'roles', 'registros', 'input'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //Aca es donde voy a levantar el formulario de carga
        $roles = DB::table('roles')->orderBy('name','asc')->pluck('name','id');
        $registros = DB::table('registro_civils')->orderBy('nombreRegistro','asc')->pluck('nombreRegistro','id');
        return view('usuarios.crear', compact('roles', 'registros'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //Aca se procesa todo lo que sea logica para luego guardar registros
        $this->validate($request, [
            'name' => 'required|min:5|max:50|regex:/^(?=.{3,50}$)[a-zñA-ZÑ](\s?[a-zñA-ZÑ])*$/',
            'documento' => 'required|min:5|max:12|unique:users,documento',
            'email' => 'required|email|unique:users,email',
            'password' => 'required|same:confirm-password|regex:^(?=\w*\d)(?=\w*[A-Z])(?=\w*[a-z])\S{8,16}$^',
            'roles' => 'required',
        ]);
        $input = $request->all();
        $input['password'] = Hash::make($input['password']);

        $user = User::create($input);
        $user->assignRole($request->input('roles'));
        toastr()->success('Usuario creado exitosamente !!', 'Aviso!');
        
        return redirect()->route('usuarios.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        $roles = DB::table('roles')->orderBy('name','asc')->pluck('name','id');
        $registros = DB::table('registro_civils')->orderBy('nombreRegistro','asc')->pluck('nombreRegistro','id');
        $userRole = null;
        if (count($user->roles) > 0) $userRole = $user->roles[0]->id;
        
        return view('usuarios.editar', compact('user', 'roles', 'userRole', 'registros'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //similar al store, es para guardar en BD lo que vamos a editar
        $validator = $this->validate($request, [
            'name' => 'required',
            'documento' => 'required|min:5|max:12|unique:users,documento,' . $id,
            'email' => 'required|email|unique:users,email,' . $id,
            'roles' => 'sometimes',
        ]);
        if (!empty($request->password)) {
            $validator = $this->validate($request, [
                'password' => 'same:confirm-password|regex:^(?=\w*\d)(?=\w*[A-Z])(?=\w*[a-z])\S{8,16}$^',
            ]);
        }
        $input = $request->all();
        if (!empty($input['password'])) {
            $input['password'] = Hash::make($input['password']);
        } else {
            $input = Arr::except($input, array('password'));
        }
        
        $user = User::find($id);
        
        $user->update($input);
        if (!empty($request->roles)) {
            DB::table('model_has_roles')->where('model_id', $id)->delete();
            $user->assignRole($request->input('roles'));
        }
        toastr()->success('Usuario modificado exitosamente !!', 'Aviso!');

        return redirect()->route('usuarios.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $usuario=User::find($id);
        if (!empty($usuario)) {
            $usuario->estado = $usuario->estado=='activo'?'inactivo':'activo';
            $usuario->update();
            toastr()->success('Estado modificado exitosamente !!', 'Aviso!');
        }else{
            toastr()->error('Usuario no encontrado!!', 'Error!');
        }
        
        return redirect()->route('usuarios.index');
    }  
}

resources/views/usuarios/crear.blade.php
@extends('adminlte::page')

@section('content')
{{ mostrar_miga([['link' => route('home'), 'titulo' => 'Inicio'], ['link' => route('usuarios.index'), 'titulo' => 'Gestión de usuarios'], ['titulo' => 'Cargar usuario']]) }}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">Cargar usuarios</div>
                    <div class="card-body">
                        @include('errors')
                        {!! Form::open(['route' => 'usuarios.store', 'method' => 'POST']) !!}
                        @csrf
                        {!! Form::hidden('estado', 'activo') !!}
                        <div class="row">
                            <div class="col-lg-5">
                                <label for="roles" class="form-label">Roles</label>&nbsp;&nbsp;<i>(Obligatorio)</i>
                                {!! Form::select('roles', $roles, null, ['class' => 'form-control', 'placeholder' => 'Seleccione una opción']) !!}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-lg-5">
                                <label for="roles" class="form-label">Registro</label>
                                {!! Form::select('registro_id', $registros, null, [
                                    'class' => 'form-control',
                                    'placeholder' => 'Seleccione una opción',
                                ]) !!}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-lg-5">
                                <label for="documento" class="form-label">Número de
                                    Documento</label>&nbsp;&nbsp;<i>(Obligatorio)</i>
                                {{ Form::number('documento', null, ['class' => 'form-control']) }}
                                <i>Debe tener un mínimo de 5 números y un máximo de 12</i>
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-lg-5">
                                <label for="name" class="form-label">Nombre y
                                    Apellido</label>&nbsp;&nbsp;<i>(Obligatorio)</i>
                                {{ Form::text('name', null, ['class' => 'form-control']) }}
                                <i>Debe tener un mínimo de 3 caracteres y un máximo de 50</i>
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-lg-5">
                                <label for="email" class="form-label">Email</label>&nbsp;&nbsp;<i>(Obligatorio)</i>
                                {{ Form::text('email', null, ['class' => 'form-control', 'minlength' => '3', 'maxlength' => '50', 'required']) }}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-lg-5">
                                <label for="password" class="form-label">Contraseña</label>&nbsp;&nbsp;<i>(Obligatorio)</i>
                                {{ Form::password('password', ['class' => 'form-control', 'id' => 'clave']) }}
                                <span
                                    style="position: absolute;right: 15px;top: 37px;padding: 1px 5px;background-color: #dadada;cursor: pointer;"
                                    onclick="mostrar_ocultar_pass(document.getElementById('clave'), this);">Mostrar</span>
                                <i>La contraseña debe tener al entre 8 y 16 caracteres, al menos un dígito, al menos una
                                    minúscula y al menos una mayúscula. NO puede tener otros símbolos.</i>
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-lg-5">
                                <label for="confirm-password" class="form-label">Confirmar
                                    contraseña</label>&nbsp;&nbsp;<i>(Obligatorio)</i>
                                {{ Form::password('confirm-password', ['class' => 'form-control', 'id' => 'clave_confirmar']) }}
                                <span
                                    style="position: absolute;right: 15px;top: 37px;padding: 1px 5px;background-color: #dadada;cursor: pointer;"
                                    onclick="mostrar_ocultar_pass(document.getElementById('clave_confirmar'), this);">Mostrar</span>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col text-right">
                                <a class="btn btn-danger" href="{{ route('usuarios.index') }}">Cancelar&nbsp;&nbsp;<i class="fa fa-times"
                                        aria-hidden="true"></i></a>
                                <button type="submit" class="btn btn-success">Guardar&nbsp;&nbsp;<i
                                        class="fa fa-save"></i></button>
                            </div>
                        </div>
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
    </div>
@endsection
<script>
    function mostrar_ocultar_pass(e, t) {
        if (e.type == 'text') {
            var tipo = 'password';
            var tag = 'Mostrar'
        } else {
            var tipo = 'text';
            var tag = 'Ocultar'
        }
        e.type = tipo;
        t.textContent = tag;
    }
</script>

resources/views/usuarios/editar.blade.php
@extends('adminlte::page')

@section('content')
{{ mostrar_miga([['link' => route('home'), 'titulo' => 'Inicio'], ['link' => route('usuarios.index'), 'titulo' => 'Gestión de usuarios'], ['titulo' => 'Editar usuario']]) }}
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-lg-12">
                <div class="card">
                <div class="card-header">Editar Usuario</div>
                    <div class="card-body">
                        @include('errors')
                        {!! Form::model($user, ['method' => 'PUT', 'route' => ['usuarios.update', $user->id]]) !!}
                        @csrf
                        <div class="row">
                            <div class="col-lg-5">
                                <label for="roles" class="form-label">Roles</label>&nbsp;&nbsp;<i>(Obligatorio)</i>
                                @if ($user->id > 1)
                                {!! Form::select('roles[]', $roles, $userRole, ['class' => 'form-control', 'placeholder' => 'Seleccione una opción']) !!}
                                @endif
                                @if ($user->id == 1)
                                {!! Form::select('roles[]', $roles, $userRole, ['class' => 'form-control', 'placeholder' => 'Seleccione una opción' , 'disabled' => true]) !!}
                                @endif
                            </div>
                        </div>
                        <br><div class="row">
                            <div class="col-lg-5">
                                <label for="roles" class="form-label">Registro</label>
                                {!! Form::select('registro_id', $registros, $user->registro_id, ['class' => 'form-control', 'placeholder' => 'Seleccione una opción']) !!}
                            </div>
                        </div>
                        <br><div class="row">
                            <div class="col-lg-5">
                                <label for="documento" class="form-label">Número de Documento</label>&nbsp;&nbsp;<i>(Obligatorio)</i>
                                {{ Form::number('documento', null, ['class' => 'form-control', 'minlength' => '5', 'maxlength' => '12', 'required']) }}
                                <i>Debe tener un mínimo de 5 números y un máximo de 12</i>
                            </div>
                        </div>
                        <br><div class="row">
                            <div class="col-lg-5">
                                <label for="name" class="form-label">Nombre y Apellido</label>&nbsp;&nbsp;<i>(Obligatorio)</i>
                                {{ Form::text('name', null, ['class' => 'form-control', 'minlength' => '3', 'maxlength' => '50', 'required']) }}
                                <i>Debe tener un mínimo de 3 caracteres y un máximo de 50</i>
                            </div>
                        </div>
                        <br><div class="row">
                            <div class="col-lg-5">
                                <label for="email" class="form-label">Email</label>&nbsp;&nbsp;<i>(Obligatorio)</i>
                                {{ Form::text('email', null, ['class' => 'form-control', 'minlength' => '3', 'maxlength' => '50', 'required']) }}
                            </div>
                        </div>
                        <hr>
                    <div class="row">
						<div class="col text-right">
							<a class="btn btn-danger" href="{{ route('usuarios.index') }}">Cancelar&nbsp;&nbsp;<i class="fa fa-times" aria-hidden="true"></i></a>
							<button type="submit" class="btn btn-success">Guardar&nbsp;&nbsp;<i class="fa fa-save"></i></button>
						</div>
					</div>
                        {!! Form::close() !!}
                    </div>
                </div>
        </div>
    </div>
</div>
@endsection
<script>
function mostrar_ocultar_pass(e, t) {
  if (e.type == 'text') {
    var tipo = 'password';
    var tag = 'Mostrar'
  } else {
    var tipo = 'text';
    var tag = 'Ocultar'
  }
  e.type = tipo;
  t.textContent = tag;
}
</script>

resources/views/usuarios/index.blade.php
@extends('adminlte::page')

@section('content')
{{ mostrar_miga([['link' => route('home'), 'titulo' => 'Inicio'], ['titulo' => 'Gestión de usuarios']]) }}
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-lg-12">
            <div class="card">
			<div class="card-header">Gestión de usuarios</div>
                <div class="card-body">
					@include('errors')
                    {!! Form::open(['route' => 'usuarios.index', 'method' => 'GET','role'=>'search']) !!}
					@csrf
										<div class="row">
											<div class="col-lg-4">
												<label for="busquedaNombre" class="form-label">Número de documento</label>
												{{ Form::number('busquedaDNI', @$input['busquedaDNI'], ['class' => 'form-control', 'placeholder' => 'Número de documento', 'pattern' =>'[0-9]+', 'minlength' => '6', 'maxlength' => '8']) }}
											</div>
											<div class="col-lg-4">
												<label for="busquedaNombre" class="form-label">Nombre y apellido</label>
												{{ Form::text('busquedaNombre', @$input['busquedaNombre'], ['class' => 'form-control', 'placeholder' => 'Nombre', 'minlength' => '3', 'maxlength' => '50']) }}
											</div>
											<div class="col-lg-4">
												<label for="busquedaEmail" class="form-label">Email</label>
												{{ Form::text('busquedaEmail', @$input['busquedaEmail'], ['class' => 'form-control', 'placeholder' => 'Email', 'minlength' => '3', 'maxlength' => '50']) }}
											</div>
											<div class="col-lg-4">
												<label for="busquedaRol" class="form-label">Rol</label>
												{{ Form::select('busquedaRol', $roles, @$input['busquedaRol'], ['class' => 'form-control', 'placeholder' => 'Seleccione una opción' ]) }}
											</div>
											<div class="col-lg-4">
												<label for="busquedaEstado" class="form-label">Estado</label>
												{{ Form::select('busquedaEstado', ['activo' => 'Activo', 'inactivo' => 'Inactivo'], @$input['busquedaEstado'], ['class' => 'form-control', 'placeholder' => 'Seleccione una opción' ]) }}
											</div>
											<div class="col-lg-4">
												<label for="busquedaRegistro" class="form-label">Registro</label>
												{{ Form::select('busquedaRegistro', $registros, @$input['busquedaRegistro'], ['class' => 'form-control', 'placeholder' => 'Seleccione una opción' ]) }}
											</div>
										</div>
										<br>
                        <div class="row">
                            <div class="col text-right">
                            <a class="btn btn-default" href="{{ route('usuarios.index') }}">Limpiar&nbsp;&nbsp;<span class="fa fa-eraser"></span></a></a>
                            <button type="submit" class="btn btn-secondary">Buscar&nbsp;&nbsp;<span class="fa fa-search"></span></button></button>
                            </div>
                        </div>
                    {!! Form::close() !!}
                    <hr>
					@can('crear-usuarios')
					<div class="row mb-1">
						<div class="col-lg-12">
														<a class="btn btn-success float-right" href="{{ route('usuarios.create') }}">Nuevo&nbsp;&nbsp;<span class="fa fa-plus"></span></a>
						</div>
					</div>
					@endcan
                    <table class="table table-striped table-responsive w-100 d-md-table">
						<thead>
							<th class="text-right" style="color:#fff;">Número de documento</th>
							<th class="text-left" style="color:#fff;">Nombre y apellido</th>
							<th class="text-left" style="color:#fff;">Email</th>
							<th class="text-left" style="color:#fff;">Rol</th>
							<th class="text-left" style="color:#fff;">Registro</th>
							<th class="text-left" style="color:#fff;">Estado</th>
							<th class="text-center" style="color:#fff;">Acciones</th>
						</thead>
						<tbody>
								@if(count($usuarios) < 0)
									<tr><td colspan="6" class="text-center">No se encontraron datos</td></tr>
								@endif
								@foreach ($usuarios as $item)
										<tr>
												<td class="text-right">{{ $item->documento }}</td>
												<td>{{ $item->name }}</td>
												<td>{{ $item->email }}</td>
												<td>
													@if (!empty($item->getRoleNames()))
														@foreach ($item->getRoleNames() as $rolName)
															<span>{{ $rolName }}</span>
														@endforeach
													@endif
												</td>
												<td>@if (!empty($item->registro_id)) {{ $registros[$item->registro_id] }} @endif</td>
												<td>{{ ucwords($item->estado) }}</td>
												<td class="text-center">
														@can('editar-usuarios')
															<a title="Editar" class="fa fa-pen" href="{{ route('usuarios.edit', $item->id) }}"></a>
														@endcan
														&nbsp;&nbsp;
														@can('borrar-rol')
															@if ($item->estado == 'activo' && $item->id != Auth::user()->id)
																<a title="Desactivar" class="fa fa-toggle-off" href="{{ route('usuarios.delete', $item->id) }}" onclick="return confirm('¿Confirma que quiere desactivar este usuario?')"></a>
															@endif
															@if ($item->estado == 'inactivo' && $item->id != Auth::user()->id)
																<a title="Activar" class="fa fa-toggle-on" href="{{ route('usuarios.delete', $item->id) }}" onclick="return confirm('¿Confirma que quiere activar este usuario?')"></a>
															@endif
														@endcan
												</td>
										</tr>
								@endforeach
						</tbody>
					</table>
					@if(count($usuarios) > 0)
					<div class="pagination justify-content-end">
						{!! $usuarios->appends($input)->links() !!}
					</div>
					@endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection