routes/web.php
<?php

use App\Http\Controllers\FolioController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RolController;
use App\Http\Controllers\UsuarioController;
use App\Http\Controllers\RegistroCivilController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function(){return view('auth.login');});
Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', [HomeController::class, 'index'])->name('home');
    Route::get('folios/limpiar', [FolioController::class, 'limpiar'])->name('folios.limpiar');
    Route::get('historial/limpiarHistorial', [FolioController::class, 'limpiar_hisrial'])->name('folios.limpiarHistorial');
    Route::resource('roles', RolController::class);
    Route::resource('usuarios', UsuarioController::class);
    Route::resource('folios', FolioController::class);
    Route::resource('registroCivil', RegistroCivilController::class);
    Route::get('/consulta', [FolioController::class, 'getFormularioConsulta'])->name('consulta');
    Route::post('/consulta', [FolioController::class, 'postFormularioConsulta'])->name('postconsulta');
    Route::get('/error/{registro_id}', [FolioController::class, 'getErrorConsulta'])->name('errorconsulta');
    // Route::post('/historial', [FolioController::class, 'postHistorial'])->name('historialComprobantes');
    Route::get('/historial', [FolioController::class, 'postHistorial'])->name('historialComprobantes');
    Route::get('/descargar', [FolioController::class, 'postdescargar'])->name('postdescargar');
    // Route::post('/descargar', [FolioController::class, 'postdescargar'])->name('postdescargar');
    Route::get('/contacto', [HomeController::class, 'contacto'])->name('contacto');
    Route::get('folios/{folio}/delete', [FolioController::class, 'destroy'])->name('folios.delete');
    Route::get('registroCivil/{registroCivil}/delete', [RegistroCivilController::class, 'destroy'])->name('registroCivil.delete');
    Route::get('roles/{rol}/delete', [RolController::class, 'destroy'])->name('roles.delete');
    Route::get('usuarios/{usuario}/delete', [UsuarioController::class, 'destroy'])->name('usuarios.delete');
    Route::get('/registroCivilImportar/{registroCivil}', [RegistroCivilController::class, 'importarEscaneados'])->name('registroCivil.importar');
});

resources/views/roles/crear.blade.php
@extends('adminlte::page')

@section('content')
{{ mostrar_miga([['link' => route('home'), 'titulo' => 'Inicio'], ['link' => route('roles.index'), 'titulo' => 'Gestión de roles'], ['titulo' => 'Cargar rol']]) }}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">Cargar rol</div>
                    <div class="card-header"></div>
                    <div class="card-body">
                        @include('errors')
                        {!! Form::open(['route' => 'roles.store', 'method' => 'POST']) !!}
                        @csrf
                        <div class="row">
                            <div class="col-lg-4">
                                <label for="name" class="form-label">Nombre</label>
                                {{ Form::text('name', null, ['class' => 'form-control', 'minlength' => '3', 'maxlength' => '15', 'required']) }}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-lg-4">
                                <label for="" class="form-label">Permisos</label>
                                <br>
                                @foreach ($permission as $value)
                                    <label>{{ Form::checkbox('permission[]', $value->id, false, ['class' => 'name']) }}
                                        {{ $value->name }}</label>
                                    <br />
                                @endforeach
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col text-right">
                                <a class="btn btn-danger" href="{{ route('roles.index') }}">Cancelar&nbsp;&nbsp;<i class="fa fa-times"
                                        aria-hidden="true"></i></a>
                                <button type="submit" class="btn btn-success">Guardar&nbsp;&nbsp;<i
                                        class="fa fa-save"></i></button>
                            </div>
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/roles/editar.blade.php
@extends('adminlte::page')

@section('content')
{{ mostrar_miga([['link' => route('home'), 'titulo' => 'Inicio'], ['link' => route('roles.index'), 'titulo' => 'Gestión de roles'], ['titulo' => 'Editar rol']]) }}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="card">
                <div class="card-header">Editar Rol</div>
                    <div class="card-body">
                        @include('errors')
                        {{-- {!! Form::model() !!} --}}
                        {!! Form::model($role, ['method' => 'PATCH', 'route' => ['roles.update', $role->id]]) !!}
                        @csrf
                        <div class="row">
                            <div class="col-lg-4">
                                <label for="name" class="form-label">Nombre</label>
                                {{ Form::text('name', null, ['class' => 'form-control', 'minlength' => '3', 'maxlength' => '15', 'required']) }}
                            </div>
                        </div>
                        <br><div class="row">
                            <div class="col-lg-4">
                                <label for="" class="form-label">Permisos</label>
                                <br>
                                @foreach ($permission as $value)
                                    <label>{{ Form::checkbox('permission[]', $value->id, in_array($value->id, $roles) ? true : false, ['class' => 'name']) }}
                                        {{ $value->name }}</label>
                                    <br />
                                @endforeach
                            </div>
                        </div>
                        <hr>
                    <div class="row">
						<div class="col text-right">
							<a class="btn btn-danger" href="{{ route('roles.index') }}">Cancelar&nbsp;&nbsp;<i class="fa fa-times" aria-hidden="true"></i></a>
							<button type="submit" class="btn btn-success">Guardar&nbsp;&nbsp;<i class="fa fa-save"></i></button>
						</div>
					</div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/roles/index.blade.php
@extends('adminlte::page')

@section('content')
{{ mostrar_miga([['link' => route('home'), 'titulo' => 'Inicio'], ['titulo' => 'Gestión de roles']]) }}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="card">
                <div class="card-header">Gestión de Roles</div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-lg-12 mb-1">
                        @can('crear-rol')
                            <a class="btn btn-success float-right" href="{{ route('roles.create') }}">Nuevo&nbsp;&nbsp;<span class="fa fa-plus"></span></a>
                        @endcan
                            </div>
                        </div>
                    <table class="table table-striped table-resposive">
                        <thead>
                                <th class="text-left" style="color:#fff;">Nombre</th>
                                <th class="text-center" style="color:#fff;">Acciones</th>
                            </thead>
                            <tbody>
                                @foreach ($roles as $item)
                                    <tr>
                                        <td>{{ $item->name }}</td>
                                        <td class="text-center">                                            
                                            @can('editar-rol')
                                            <a title="Editar" class="fa fa-pen" href="{{ route('roles.edit', $item->id) }}"></a>
                                            @endcan
                                            &nbsp;&nbsp;
                                            @can('borrar-rol')
                                            <a title="Borrar" class="fa fa-trash" href="{{ route('roles.delete', $item->id) }}" onclick="return confirm('¿Confirma que quiere eliminar este rol?')"></a>
                                            @endcan
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                        <div class="pagination justify-content-end">
                            {!! $roles->links() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection